# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  # This workflow tests the code
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry env use python3.10
          poetry install

      - name: check formatting
        run: |
          black --check **/*.py

      - name: Run static type analysis
        run: |
          poetry run pyright

      - name: run unittests
        run: |
          poetry run pytest --cov=schema_validator tests/
