# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the workflow will run
on:

  workflow_dispatch:

jobs:
  # This workflow tests the code
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: publish package
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
          poetry publish
